slave_name: MacSlave-CD-01
web_server: http://locahost:3000
web_logserver: http://locahost:3001
threads_number: 1
project: Demo
local_ip: 192.168.29.227
root_path: /tmp/testplus_projects
operation_system:
   type: mac
   version: 10.0
platforms:
-  type: firefox
   version: 5.1
   execute_cmd: firefox
-  type: chrome
   version: 5.1
   execute_cmd: chrome
-  type: ie
   version: 5.1
   execute_cmd: iexplore
   