slave_name: MacSlave-CD-01
web_server: http://192.168.28.210
threads_number: 6
project_names: [IronHide]
root_path: /tmp/testplus_projects
operation_system:
   type: mac
   version: 10.0
platforms:
-  type: firefox
   version: 5.1
   execute_cmd: firefox
-  type: chrome
   version: 5.1
   execute_cmd: chrome
-  type: iphone
   version: 5.1
   execute_cmd: iexplore
   