QA:
  mysql:
    adapter: mysql2
    host: 192.168.28.218
    database: ironhide_staging
    username: ironhide
    password: ironhide_staging123!
    encoding: utf8
    reconnect: false
    pool: 5   
  redis:
    host: 192.168.28.218
    port: 6379

